version: '3.8'

services:
  flutter-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./build:/app/build
    environment:
      - FLUTTER_HOME=/opt/flutter
    # This will build the APK and exit

  android-emulator:
    image: budtmo/docker-android-x86-11.0
    privileged: true
    environment:
      - DEVICE=Samsung Galaxy S10
      - APPIUM=true
    volumes:
      - ./build:/root/tmp
    ports:
      - "6080:6080"
      - "4723:4723"
      - "5554:5554"
      - "5555:5555"
    # For running Android emulator in container (optional)